spring:
  application:
    name: spring-mvc
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT
    username: root
    password: root


server:
  port: 8080

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true #开启驼峰转换
logging:
  level:
    org.apache.ibatis: debug
    com.glf.mapper: debug
